# Generated by Django 5.2.1 on 2025-05-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("IP", "In-progress"),
                            ("C", "Completed"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "ordering": ["status"],
            },
        ),
    ]
